import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import { darkModeScript } from "./lib/darkModeScript";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">       
      <head>
        <script dangerouslySetInnerHTML={{ __html: darkModeScript }} />
      </head>
      <body className={'h-[100vh] bg-colors-primary text-colors-secondary flex flex-col justify-between'}>
        <Header />
        <div className="h-full">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
